using System;
using System.Collections.Generic;
using System.Linq;
using MachOneSoftware.PizzaBuddy.Models;

namespace MachOneSoftware.PizzaBuddy
{
    static class Repo
    {
        private static Lazy<Dictionary<string, Pizza>> _meatPizzas = new Lazy<Dictionary<string, Pizza>>(() => 
            new Dictionary<string, Pizza> {
                ["Barbeque Chicken"] = new Pizza("Barbeque Chicken", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["onion"], 
                                                                   _toppings.Value["chicken"],
                                                                   _toppings.Value["bbq sauce"]}),
                ["Beef Lovers"] = new Pizza("Beef Lovers", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["pepperoni"], 
                                                                   _toppings.Value["beef"]}),
                ["Breakfast"] = new Pizza("Breakfast", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["bacon"],
                                                                   _toppings.Value["boiled egg"]}),
                ["Buffalo Chicken"] = new Pizza("Buffalo Chicken", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["chicken"], 
                                                                   _toppings.Value["buffalo sauce"]}),
                ["Cheesesteak"] = new Pizza("Cheesesteak", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["beef"], 
                                                                   _toppings.Value["green pepper"],
                                                                   _toppings.Value["onion"],
                                                                   _toppings.Value["mushroom"]}),
                ["Chicken Bacon Alfredo"] = new Pizza("Chicken Bacon Alfredo", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["mushroom"], 
                                                                   _toppings.Value["onion"],
                                                                   _toppings.Value["chicken"],
                                                                   _toppings.Value["bacon"]}),
                ["Chicken Feast"] = new Pizza("Chicken Feast", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["chicken"], 
                                                                   _toppings.Value["mushroom"],
                                                                   _toppings.Value["sweetcorn"]}),
                ["Deluxe Hawaiian"] = new Pizza("Deluxe Hawaiian", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["ham"], 
                                                                   _toppings.Value["bacon"],
                                                                   _toppings.Value["pineapple"]}),
                ["Diavolo"] = new Pizza("Diavolo", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["pepperoni"], 
                                                                   _toppings.Value["salami"],
                                                                   _toppings.Value["onion"]}),
                ["Emiliana"] = new Pizza("Emiliana", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["tomato"], 
                                                                   _toppings.Value["mozzarella cheese"],
                                                                   _toppings.Value["eggplant"],
                                                                   _toppings.Value["potato"],
                                                                   _toppings.Value["sausage"]}),
                ["Four Seasons"] = new Pizza("Four Seasons", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["tomato"], 
                                                                   _toppings.Value["mozzarella cheese"],
                                                                   _toppings.Value["basil leaves"],
                                                                   _toppings.Value["artichoke"],
                                                                   _toppings.Value["fontina cheese"],
                                                                   _toppings.Value["mushroom"],
                                                                   _toppings.Value["red pepper"],
                                                                   _toppings.Value["provolone cheese"],
                                                                   _toppings.Value["potato"],
                                                                   _toppings.Value["pecorino cheese"]}),
                ["Hawaiian"] = new Pizza("Hawaiian", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["ham"],
                                                                   _toppings.Value["pineapple"]}),
                ["Hawaiian Elvis"] = new Pizza("Hawaiian Elvis", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["canadian bacon"], 
                                                                   _toppings.Value["pineapple"],
                                                                   _toppings.Value["sauerkraut"]}),
                ["Meat Lovers"] = new Pizza("Meat Lovers", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["pepperoni"], 
                                                                   _toppings.Value["beef"],
                                                                   _toppings.Value["sausage"],
                                                                   _toppings.Value["ham"]}),
                ["New York Classic"] = new Pizza("New York Classic", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["double cheese"], 
                                                                   _toppings.Value["pepperoni"],
                                                                   _toppings.Value["hot chorizo sausage"]}),
                ["Pepperoni Bacon"] = new Pizza("Pepperoni Bacon", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["pepperoni"], 
                                                                   _toppings.Value["bacon"]}),
                ["Pepperoni Passion"] = new Pizza("Pepperoni Passion", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["pepperoni"]}),
                ["Pepperoni Veggie"] = new Pizza("Pepperoni Veggie", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["pepperoni"], 
                                                                   _toppings.Value["onion"],
                                                                   _toppings.Value["green pepper"]}),
                ["Philly Cheesesteak"] = new Pizza("Philly Cheesesteak", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["mozzarella cheese"], 
                                                                   _toppings.Value["seasoned steak"],
                                                                   _toppings.Value["bell peppers"]}),
                ["Prosciutto and Arugula"] = new Pizza("Prosciutto and Arugula", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["mozzarella chesse"], 
                                                                   _toppings.Value["parmesan"],
                                                                   _toppings.Value["prosciutto"],
                                                                   _toppings.Value["arugula"]}),
                ["Ranch BBQ"] = new Pizza("Ranch BBQ", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["chicken"], 
                                                                   _toppings.Value["pepperoni"],
                                                                   _toppings.Value["beef"],
                                                                   _toppings.Value["bacon"]}),
                ["Regina"] = new Pizza("Regina", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["ham"], 
                                                                   _toppings.Value["artichoke"],
                                                                   _toppings.Value["mozzarella"],
                                                                   _toppings.Value["olive"]}),
                ["Seafood"] = new Pizza("Seafood", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["shrimp"], 
                                                                   _toppings.Value["anchovy"],
                                                                   _toppings.Value["basil"]}),
                ["Supreme"] = new Pizza("Supreme", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["pepperoni"], 
                                                                   _toppings.Value["sausage"],
                                                                   _toppings.Value["mushroom"],
                                                                   _toppings.Value["green pepper"],
                                                                   _toppings.Value["onion"]}),
                ["Texas BBQ"] = new Pizza("Texas BBQ", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["chicken"], 
                                                                   _toppings.Value["bacon"],
                                                                   _toppings.Value["onion"],
                                                                   _toppings.Value["red pepper"],
                                                                   _toppings.Value["green pepper"]}),
                ["Tuna Supreme"] = new Pizza("Tuna Supreme", 
                                                 PizzaType.Carnivore,
                                                 new List<Topping>{_toppings.Value["tuna"], 
                                                                   _toppings.Value["sweetcorn"],
                                                                   _toppings.Value["onion"]})
            });
            
        private static Lazy<Dictionary<string, Pizza>> _veggiePizzas = new Lazy<Dictionary<string, Pizza>>(() =>
            new Dictionary<string, Pizza> {
                ["Balkan"] = new Pizza("Balkan",
                                        PizzaType.Veggie,
                                        new List<Topping>{_toppings.Value["goat cheese"],
                                                          _toppings.Value["cherry tomato"],
                                                          _toppings.Value["black olive"]}),
                ["Four cheese"] = new Pizza("Four cheese",
                                        PizzaType.Veggie,
                                        new List<Topping>{_toppings.Value["riccota"],
                                                          _toppings.Value["parmigian"],
                                                          _toppings.Value["mozzarella"],
                                                          _toppings.Value["gorgonzola"]}),
                ["Margherita"] = new Pizza("Margherita",
                                        PizzaType.Vegan,
                                        new List<Topping>{_toppings.Value["basil"],
                                                          _toppings.Value["tomato"],
                                                          _toppings.Value["garlic"]}),
                ["Mushroom Broccol"] = new Pizza("Mushroom Broccol",
                                        PizzaType.Vegan,
                                        new List<Topping>{_toppings.Value["mushroom"],
                                                          _toppings.Value["broccoli"]}),
                ["Neopolitan"] = new Pizza("Neopolitan",
                                        PizzaType.Veggie,
                                        new List<Topping>{_toppings.Value["basil leaves"],
                                                          _toppings.Value["tomato"],
                                                          _toppings.Value["mozarella cheese"]}),
                ["Parmigiana"] = new Pizza("Parmigiana",
                                        PizzaType.Vegan,
                                        new List<Topping>{_toppings.Value["tomato"],
                                                          _toppings.Value["eggplant"]}),
                ["Spice Garden"] = new Pizza("Spice Garden",
                                        PizzaType.Vegan,
                                        new List<Topping>{_toppings.Value["green pepper"],
                                                          _toppings.Value["banana pepper"],
                                                          _toppings.Value["jalapeño pepper"]}),
                ["Spinach Delight"] = new Pizza("Spinach Delight",
                                        PizzaType.Veggie,
                                        new List<Topping>{_toppings.Value["spinach"],
                                                          _toppings.Value["tomato"]}),
                ["Veggie Lovers"] = new Pizza("Veggie Lovers",
                                        PizzaType.Vegan,
                                        new List<Topping>{_toppings.Value["spinach"],
                                                          _toppings.Value["olive"],
                                                          _toppings.Value["mushroom"],
                                                          _toppings.Value["onion"],
                                                          _toppings.Value["tomato"]})
            }
        );

        private static Lazy<Dictionary<string, Topping>> _toppings = new Lazy<Dictionary<string, Topping>>(() =>
        new Dictionary<string, Topping>
        {   
            ["anchovy"] =               new Topping("anchovy", ToppingType.Meat),
            ["bacon"] =                 new Topping("bacon", ToppingType.Meat),
            ["beef"] =                  new Topping("beef", ToppingType.Meat),
            ["boiled egg"] =            new Topping("boiled egg", ToppingType.Meat),
            ["canadian bacon"] =        new Topping("canadian bacon", ToppingType.Meat),
            ["chicken"] =               new Topping("chicken", ToppingType.Meat),
            ["ham"] =                   new Topping("ham", ToppingType.Meat),
            ["hot chorizo sausage"] =   new Topping("hot chorizo sausage", ToppingType.Meat),
            ["pepperoni"] =             new Topping("pepperoni", ToppingType.Meat),
            ["prosciutto"] =            new Topping("prosciutto", ToppingType.Meat),
            ["salami"] =                new Topping("salami", ToppingType.Meat),
            ["sausage"] =               new Topping("sausage", ToppingType.Meat),
            ["shrimp"] =                new Topping("shrimp", ToppingType.Meat),
            ["steak"] =                 new Topping("steak", ToppingType.Meat),
            ["tuna"] =                  new Topping("tuna", ToppingType.Meat),

            ["artichoke"] =             new Topping("artichoke", ToppingType.Veggie),
            ["arugula"] =               new Topping("arugula", ToppingType.Veggie),
            ["banana pepper"] =         new Topping("banana pepper", ToppingType.Veggie),
            ["basil"] =                 new Topping("basil", ToppingType.Veggie),
            ["basil leaves"] =          new Topping("basil leaves", ToppingType.Veggie),
            ["bell peppers"] =          new Topping("bell peppers", ToppingType.Veggie),
            ["black olive"] =           new Topping("black olive", ToppingType.Veggie),
            ["broccoli"] =              new Topping("broccoli", ToppingType.Veggie),
            ["cherry tomato"] =         new Topping("cherry tomato", ToppingType.Veggie),
            ["eggplant"] =              new Topping("eggplant", ToppingType.Veggie),
            ["garlic"] =                new Topping("garlic", ToppingType.Veggie),
            ["goat cheese"] =           new Topping("goat cheese", ToppingType.Veggie),
            ["gorgonzola"] =            new Topping("gorgonzola", ToppingType.Veggie),
            ["green pepper"] =          new Topping("green pepper", ToppingType.Veggie),
            ["jalapeño pepper"] =       new Topping("jalapeño pepper", ToppingType.Veggie),
            ["mozzarella"] =            new Topping("mozzarella", ToppingType.Veggie),
            ["mushroom"] =              new Topping("mushroom", ToppingType.Veggie),
            ["olive"] =                 new Topping("olive", ToppingType.Veggie),
            ["onion"] =                 new Topping("onion", ToppingType.Veggie),
            ["parmigian"] =             new Topping("parmigian", ToppingType.Veggie),
            ["pineapple"] =             new Topping("pineapple", ToppingType.Veggie),
            ["potato"] =                new Topping("potato", ToppingType.Veggie),
            ["red onion"] =             new Topping("red onion", ToppingType.Veggie),
            ["red pepper"] =            new Topping("red pepper", ToppingType.Veggie),
            ["riccota"] =               new Topping("riccota", ToppingType.Veggie),
            ["sauerkraut"] =            new Topping("sauerkraut", ToppingType.Veggie),
            ["spinach"] =               new Topping("spinach", ToppingType.Veggie),
            ["sweetcorn"] =             new Topping("sweetcorn", ToppingType.Veggie),
            ["tomato"] =                new Topping("tomato", ToppingType.Veggie)
       });

        public static IEnumerable<KeyValuePair<string, Pizza>> MeatPizzas { get => _meatPizzas.Value; }
        public static IEnumerable<KeyValuePair<string, Pizza>> VeggiePizzas { get => _veggiePizzas.Value; }
        public static IEnumerable<KeyValuePair<string, Pizza>> AllPizzas { get => _meatPizzas.Value.Concat(_veggiePizzas.Value); }
        public static IEnumerable<Topping> Meats { get => _toppings.Value.Values.Where(t => t.ToppingType == ToppingType.Meat); }
        public static IEnumerable<Topping> Veggies { get => _toppings.Value.Values.Where(t => t.ToppingType == ToppingType.Veggie); }
        public static IEnumerable<Topping> AllToppings { get => _toppings.Value.Values; }
    }
}
